[package]
name = "wikipedia"
version = "0.1.0"
authors = ["Yusuf Irwandi <yusuf.chapterzero@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
